apiVersion: v1
kind: Namespace
metadata:
  name: ms
  labels:
    istio-injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: zonex5cpb/service-a:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: ms
spec:
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer    
